# Generated by Django 2.2.4 on 2023-06-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pypie_app', '0002_auto_20230613_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='pypie',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
