# Generated by Django 2.2.4 on 2023-06-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('pypie_app', '0003_pypie_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pypie',
            name='user_voted',
            field=models.ManyToManyField(related_name='voted_pies', to='login_app.User'),
        ),
    ]
